use_frameworks!

platform :ios, '8.0'

target 'GFImageFullScreen_Example' do
  pod 'GFImageFullScreen', :path => '../'

  target 'GFImageFullScreen_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
