use_frameworks!

platform :ios, '9.3'

target 'GFImageFullScreen_Example' do
  pod 'GFImageFullScreen', :path => '../'
  pod 'iOS-Color-Picker'

  target 'GFImageFullScreen_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
